stages:
  - deploy

image: node:alpine

cache:
  paths:
  - node_modules/

before_script:
  - npm set progress=false

deploy-production:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apk update && apk add --no-cache bash openssh )'
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - npm i pm2 -g
    - pm2 deploy ecosystem.json production setup
    - pm2 deploy ecosystem.json production --force
  environment:
    name: production
    url: https://www.manda.web.id
  tags:
    - docker
    - ubuntu
  only:
    - master