name: Publish Release

env:
  DOCKERHUB_REGISTRY: registry.hub.docker.com
  IMAGES_NAME: portofolio

on: 
  push:
    branches:
      - "master"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    environment: "production"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get project version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: Set up QEMU dependency
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "."
          push: true
          tags: |
            ${{ env.IMAGES_NAME }}:latest
            ${{ env.IMAGES_NAME }}:${{ steps.package-version.outputs.current-version}}
      - name: Wait for build to succeed
        uses: fountainhead/action-wait-for-check@v1.1.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
  
  release-code:
    runs-on: ubuntu-latest
    needs: build
    if: steps.wait-for-build.outputs.conclusion == "success"
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}